### ISSUE TITLE
kbaba1001 さんとの交流会

### ISSUE THREAD

**Issue by snoozer05** [ruby-sapporo/ruby-sapporo.org#50]
https://twitter.com/kbaba1001/status/759968227145359361

8/15-8/21くらいで札幌にお越しになる kbaba1001 さんが、札幌滞在中にRuby札幌の人たちと交流できたらなーとのことなのですが、ぼく以外で一緒に交流していただけそうな方はいらっしゃいますか？

**Comment by tricknotes** [comment]
交流しましょう！

**Comment by niku** [comment]
はい ノ

**Comment by imaz** [comment]
参加したいです

**Comment by snoozer05** [comment]
19(金)の夜にえにしテックでミートアップ的な感じでやってみましょう〜

**Comment by snoozer05** [comment]
と思ったら、19は kbaba1001さん(と、もう１名いらっしゃるとのことです）の方の都合があんまりだったので、18(木)の19:00〜えにしテックでやることにしましょうー

**Comment by niku** [comment]
木曜日だ！
もしよければサッポロビームをそこで同時開催させてもらえませんか．
そしたら私も行けるなあ．

**Comment by snoozer05** [comment]
@niku やりましょう！

**Comment by snoozer05** [comment]
たのしかった！
